Chaging promote logic, adding artifact

diff --git a/.gitlab/ci/templates/update-chart-tag-template.yml b/.gitlab/ci/templates/update-chart-tag-template.yml
--- a/.gitlab/ci/templates/update-chart-tag-template.yml
+++ b/.gitlab/ci/templates/update-chart-tag-template.yml
@@ -28,23 +28,35 @@
     - |
       if [ "$USERNAME" = "gitlab-ci-token" ]; then
         echo "INFO: gitlab-ci-token can't push to a different project, skipping tag push"
-        exit 0
+        SKIP_PUSH="true"
       fi
 
     - |  
       if [ -z "$TOKEN" ]; then
         echo "INFO: Token can't be empty, skipping tag push"
+        SKIP_PUSH="true"
+      fi
+
+    - |
+      if [ "$SKIP_PUSH" = "true" ]; then
+        echo "TAG_PUSHED=skipped" > result.env
         exit 0
       fi
 
   script:
-    - WORKING_BRANCH="$CI_COMMIT_REF_NAME"
-    - HELM_REPO_URL="https://${USERNAME}:${TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${REPO}"
-    
-    - git clone "$HELM_REPO_URL"
-    - cd "$REPO"
-    
     - |
+      echo "Trying to push Tag to Deploy Repo"
+
+      set -e
+
+      trap 'echo "TAG_PUSHED=failure" > result.env' ERR
+
+      WORKING_BRANCH="$CI_COMMIT_REF_NAME"
+      HELM_REPO_URL="https://${USERNAME}:${TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${REPO}"
+
+      git clone "$HELM_REPO_URL"
+      cd "$REPO"  
+
       # Check if branch exists on remote...
       if git ls-remote --exit-code --heads origin "$WORKING_BRANCH" > /dev/null; then
         git checkout "$WORKING_BRANCH"
@@ -53,14 +65,12 @@
         git checkout -b "$WORKING_BRANCH" origin/main
       fi
 
-    - |
       echo "Updating tag in $CHART_PATH/$VALUES_FILE"
       cd "$CHART_PATH"
       ls -l $VALUES_FILE
 
       yq e -i '.image.tag = env(TAG)' $VALUES_FILE
 
-    - |
       if ! git diff --quiet -- "$VALUES_FILE"; then
         echo "Image tag changed in $VALUES_FILE, committing and pushing..."
         git add $VALUES_FILE
@@ -69,7 +79,13 @@
       else
         echo "No change in $VALUES_FILE, nothing to deploy"
       fi
+      
+      echo "TAG_PUSHED=success" > result.env
 
+  artifacts:
+      when: always
+      reports:
+        dotenv: result.env
 
 # -----------------------------------------------------------------------------------------
 # Trigger pipeline via API
@@ -92,6 +108,7 @@
 
     - |
       echo "Showing variables for debug purpose..."
+      echo "TAG_PUSHED = $TAG_PUSHED"
       echo "UPDATED_IMAGENAME = $UPDATED_IMAGENAME"
       echo "UPDATED_TAG = $UPDATED_TAG"
       echo "REF = $REF"
@@ -101,7 +118,7 @@
     - >
       RESPONSE="$(curl -s -X POST \
       --fail \
-      --form "token=$DEPLOY_TRIGGER_TOKEN" \
+      --form "token=$TRIGGER_TOKEN" \
       --form "ref=$REF" \
       --form "variables[UPDATED_IMAGENAME]=$UPDATED_IMAGENAME" \
       --form "variables[UPDATED_TAG]=$UPDATED_TAG" \
