Update promote logic

diff --git a/.gitlab/ci/templates/update-chart-tag-template.yml b/.gitlab/ci/templates/update-chart-tag-template.yml
--- a/.gitlab/ci/templates/update-chart-tag-template.yml
+++ b/.gitlab/ci/templates/update-chart-tag-template.yml
@@ -27,9 +27,15 @@
   before_script:
     - |
       if [ "$USERNAME" = "gitlab-ci-token" ]; then
-        echo "ERROR: gitlab-ci-token can't push to a different project"
+        echo "ERROR: gitlab-ci-token can't push to a different project, skipping tag push"
         exit 1
       fi
+      
+      if [ -z "$USERNAME" ]; then
+        echo "ERROR: Token can't be empty, skipping tag push"
+        exit 1
+      fi
+
   script:
     - WORKING_BRANCH="$CI_COMMIT_REF_NAME"
     - HELM_REPO_URL="https://${USERNAME}:${TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${REPO}"
